# Site settings
title: Aidan Malone
email: a_s_malone@hotmail.com

#Site description
description: > # this means to ignore newlines until "baseurl:"
  The design portfolio of a serial creator, covering everything from coding to blacksmithing.

#Settings for the URL
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: A-Malone

#5 posts per page
paginate: 5

# Build settings
markdown: kramdown

#URL settings
permalink: "/:categories/:title"

#Category declaration
category-list: [blog, coding, design, hackathons, miscelaneous]
